services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/data/db:/data/db
    networks:
      - api
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    networks:
      - api
    depends_on:
      - db
networks:
  api:
    driver: bridge
